syntax = "proto3";

option java_package = "com.game.proto.task";

import "item/item.proto";

// 请求玩家任务列表信息消息
message CWGetPlayerTaskListMessage {
  /** 功能id */
  int32 functionId = 1;
}

// 响应玩家任务列表信息消息
message WCGetPlayerTaskListMessage {
  /** 功能id */
  int32 functionId = 1;
  /** 任务信息bean列表 */
  repeated TaskBean taskBeanList = 2;
}


// 请求玩家任务列表ByTaskType消息
message CWGetPlayerTaskListByTypeMessage {
  /** 任务类型 */
  int32 taskType = 1;
}

// 响应玩家任务列表ByTaskType消息
message WCGetPlayerTaskListByTypeMessage {
  /** 功能id */
  int32 functionId = 1;
  /** 任务信息bean列表 */
  repeated TaskBean taskBeanList = 2;
}

// 任务信息bean
message TaskBean {
  /** 任务基本信息 */
  BaseTaskBean baseTaskBean = 1;
}

// 任务基本信息
message BaseTaskBean {
  /** 任务类型 */
  int32 taskType = 1;
  /** 任务id */
  int32 taskId = 2;
  /** 任务重置类型(0: 终生不重置; 1: 每天重置; 2: 每周重置; 3: 每月重置; 4: 赛季重置) */
  int32 resetType = 3;
  /** 任务描述 */
  string desc = 4;
  /** 目标数量 */
  int64 targetNum = 5;
  /** 奖励 */
  repeated ItemBean rewards = 6;
  /** 跳转标识 */
  string guide = 7;
  /** 任务图标 */
  string icon = 8;
  /** 当前任务进度 */
  int64 currProgress = 9;
  /** 任务状态(0: 已完成(未领取); 1:未完成; 2: 已领取; 3:未解锁) */
  int32 state = 10;
}

message GetTaskRewardBean {
  /** 任务类型 */
  int32 taskType = 1;
  /** 任务id列表（不传领或-1，领取全部） */
  repeated int32 taskIds = 2;
}

// 请求领取玩家任务奖励消息
message CWGetPlayerTaskRewardMessage {
  /** 任务领奖 */
  repeated GetTaskRewardBean tasks = 1;
}

// 响应领取玩家任务奖励消息
message WCGetPlayerTaskRewardMessage {
  /** 奖励 */
  repeated ItemBean rewards = 1;
  /** 玩家活跃度 */
  int32 active = 2;
}

// 请求日常任务列表（定制化开发接口）
message CWTaskTableMessage {
}

// 响应日常任务列表（定制化开发接口）
message WCTaskTableMessage {
  /** 任务基本信息列表 */
  repeated BaseTaskBean baseTaskBeanList = 1;
}

// 请求领取任务奖励（定制化开发接口）
message CWGetTaskRewardMessage {
}

// 响应领取任务奖励（定制化开发接口）
message WCGetTaskRewardMessage {
  /** 奖励 */
  repeated ItemBean rewards = 1;
  /** 玩家活跃度 */
  int32 active = 2;
}

