
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.config.test;

import com.google.gson.JsonObject;
import com.mumu.game.luban.base.AbstractBean;


public final class DateTimeRange extends AbstractBean {
    public DateTimeRange(JsonObject _buf) {
        startTime = _buf.get("start_time").getAsLong();
        endTime = _buf.get("end_time").getAsLong();
    }

    public static DateTimeRange deserialize(JsonObject _buf) {
        return new com.mumu.game.luban.config.test.DateTimeRange(_buf);
    }

    public final long startTime;
    public final long endTime;

    public static final int __ID__ = 495315430;

    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public java.lang.String toString() {
        return "{ "
        + "startTime:" + startTime + ","
        + "endTime:" + endTime + ","
        + "}";
    }
}

