
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.config.test;

import com.google.gson.JsonObject;
import com.mumu.game.luban.base.AbstractBean;


public final class DemoSingletonType extends AbstractBean {
    public DemoSingletonType(JsonObject _buf) {
        id = _buf.get("id").getAsInt();
        name = _buf.get("name").getAsString();
        date = com.mumu.game.luban.config.test.DemoDynamic.deserialize(_buf.get("date").getAsJsonObject());
    }

    public static DemoSingletonType deserialize(JsonObject _buf) {
        return new com.mumu.game.luban.config.test.DemoSingletonType(_buf);
    }

    public final int id;
    public final String name;
    public final com.mumu.game.luban.config.test.DemoDynamic date;

    public static final int __ID__ = 539196998;

    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public java.lang.String toString() {
        return "{ "
        + "id:" + id + ","
        + "name:" + name + ","
        + "date:" + date + ","
        + "}";
    }
}

