
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.config.test;

import com.google.gson.JsonObject;
import com.mumu.game.luban.base.AbstractBean;


public final class DemoD5 extends com.mumu.game.luban.config.test.DemoDynamic {
    public DemoD5(JsonObject _buf) {
        super(_buf);
        time = com.mumu.game.luban.config.test.DateTimeRange.deserialize(_buf.get("time").getAsJsonObject());
    }

    public static DemoD5 deserialize(JsonObject _buf) {
        return new com.mumu.game.luban.config.test.DemoD5(_buf);
    }

    public final com.mumu.game.luban.config.test.DateTimeRange time;

    public static final int __ID__ = -2138341744;

    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public java.lang.String toString() {
        return "{ "
        + "x1:" + x1 + ","
        + "time:" + time + ","
        + "}";
    }
}

