
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.config.test;

import com.google.gson.JsonObject;
import com.mumu.game.luban.base.AbstractBean;


public final class DemoE2 extends AbstractBean {
    public DemoE2(JsonObject _buf) {
        { if (_buf.has("y1") && !_buf.get("y1").isJsonNull()) { y1 = _buf.get("y1").getAsInt(); } else { y1 = null; } }
        y2 = _buf.get("y2").getAsBoolean();
    }

    public static DemoE2 deserialize(JsonObject _buf) {
        return new com.mumu.game.luban.config.test.DemoE2(_buf);
    }

    public final Integer y1;
    public final boolean y2;

    public static final int __ID__ = -2138341716;

    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public java.lang.String toString() {
        return "{ "
        + "y1:" + y1 + ","
        + "y2:" + y2 + ","
        + "}";
    }
}

