
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.config.test;

import com.google.gson.JsonObject;
import com.mumu.game.luban.base.AbstractBean;
import com.mumu.game.luban.base.SerializationException;


public abstract class DemoD3 extends com.mumu.game.luban.config.test.DemoDynamic {
    public DemoD3(JsonObject _buf) {
        super(_buf);
        x3 = _buf.get("x3").getAsInt();
    }

    public static DemoD3 deserialize(JsonObject _buf) {
        switch (_buf.get("$type").getAsString()) {
            case "DemoE1": return new com.mumu.game.luban.config.test.DemoE1(_buf);
            case "test.login.RoleInfo": return new com.mumu.game.luban.config.test.login.RoleInfo(_buf);
            default: throw new SerializationException();
        }
    }

    public final int x3;


    @Override
    public java.lang.String toString() {
        return "{ "
        + "x1:" + x1 + ","
        + "x3:" + x3 + ","
        + "}";
    }
}

