
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.config.test;

import com.google.gson.JsonObject;
import com.mumu.game.luban.base.AbstractBean;


public final class DemoE1 extends com.mumu.game.luban.config.test.DemoD3 {
    public DemoE1(JsonObject _buf) {
        super(_buf);
        x4 = _buf.get("x4").getAsInt();
    }

    public static DemoE1 deserialize(JsonObject _buf) {
        return new com.mumu.game.luban.config.test.DemoE1(_buf);
    }

    public final int x4;

    public static final int __ID__ = -2138341717;

    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public java.lang.String toString() {
        return "{ "
        + "x1:" + x1 + ","
        + "x3:" + x3 + ","
        + "x4:" + x4 + ","
        + "}";
    }
}

