
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.config.test;

import com.google.gson.JsonObject;
import com.mumu.game.luban.base.AbstractBean;
import com.mumu.game.luban.base.SerializationException;


public abstract class DemoDynamic extends AbstractBean {
    public DemoDynamic(JsonObject _buf) {
        x1 = _buf.get("x1").getAsInt();
    }

    public static DemoDynamic deserialize(JsonObject _buf) {
        switch (_buf.get("$type").getAsString()) {
            case "DemoD2": return new com.mumu.game.luban.config.test.DemoD2(_buf);
            case "DemoE1": return new com.mumu.game.luban.config.test.DemoE1(_buf);
            case "test.login.RoleInfo": return new com.mumu.game.luban.config.test.login.RoleInfo(_buf);
            case "DemoD5": return new com.mumu.game.luban.config.test.DemoD5(_buf);
            default: throw new SerializationException();
        }
    }

    public final int x1;


    @Override
    public java.lang.String toString() {
        return "{ "
        + "x1:" + x1 + ","
        + "}";
    }
}

