
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.config.test;

import com.google.gson.JsonObject;
import com.mumu.game.luban.base.AbstractBean;


public final class DemoD2 extends com.mumu.game.luban.config.test.DemoDynamic {
    public DemoD2(JsonObject _buf) {
        super(_buf);
        x2 = _buf.get("x2").getAsInt();
    }

    public static DemoD2 deserialize(JsonObject _buf) {
        return new com.mumu.game.luban.config.test.DemoD2(_buf);
    }

    public final int x2;

    public static final int __ID__ = -2138341747;

    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public java.lang.String toString() {
        return "{ "
        + "x1:" + x1 + ","
        + "x2:" + x2 + ","
        + "}";
    }
}

