
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.config.test;

import com.google.gson.JsonObject;
import com.mumu.game.luban.base.AbstractBean;


public final class DemoType1 extends AbstractBean {
    public DemoType1(JsonObject _buf) {
        x1 = _buf.get("x1").getAsInt();
    }

    public static DemoType1 deserialize(JsonObject _buf) {
        return new com.mumu.game.luban.config.test.DemoType1(_buf);
    }

    public final int x1;

    public static final int __ID__ = -367048296;

    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public java.lang.String toString() {
        return "{ "
        + "x1:" + x1 + ","
        + "}";
    }
}

