
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.config.test;

import com.google.gson.JsonObject;
import com.mumu.game.luban.base.AbstractBean;


public final class MultiRowType3 extends AbstractBean {
    public MultiRowType3(JsonObject _buf) {
        id = _buf.get("id").getAsInt();
        { com.google.gson.JsonArray _json0_ = _buf.get("items").getAsJsonArray(); items = new java.util.ArrayList<com.mumu.game.luban.config.test.MultiRowType1>(_json0_.size()); for(JsonElement _e0 : _json0_) { com.mumu.game.luban.config.test.MultiRowType1 _v0;  _v0 = com.mumu.game.luban.config.test.MultiRowType1.deserialize(_e0.getAsJsonObject());  items.add(_v0); }   }
    }

    public static MultiRowType3 deserialize(JsonObject _buf) {
        return new com.mumu.game.luban.config.test.MultiRowType3(_buf);
    }

    public final int id;
    public final java.util.ArrayList<com.mumu.game.luban.config.test.MultiRowType1> items;

    public static final int __ID__ = 540474972;

    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public java.lang.String toString() {
        return "{ "
        + "id:" + id + ","
        + "items:" + items + ","
        + "}";
    }
}

