
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.config.test;

import com.google.gson.JsonObject;
import com.mumu.game.luban.base.AbstractBean;


public final class NotIndexList extends AbstractBean {
    public NotIndexList(JsonObject _buf) {
        x = _buf.get("x").getAsInt();
        y = _buf.get("y").getAsInt();
    }

    public static NotIndexList deserialize(JsonObject _buf) {
        return new com.mumu.game.luban.config.test.NotIndexList(_buf);
    }

    public final int x;
    public final int y;

    public static final int __ID__ = -50446599;

    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public java.lang.String toString() {
        return "{ "
        + "x:" + x + ","
        + "y:" + y + ","
        + "}";
    }
}

