
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.config.test;

import com.google.gson.JsonObject;
import com.mumu.game.luban.base.AbstractBean;


public final class Path extends AbstractBean {
    public Path(JsonObject _buf) {
        id = _buf.get("id").getAsInt();
        res = _buf.get("res").getAsString();
    }

    public static Path deserialize(JsonObject _buf) {
        return new com.mumu.game.luban.config.test.Path(_buf);
    }

    public final int id;
    public final String res;

    public static final int __ID__ = -1226450911;

    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public java.lang.String toString() {
        return "{ "
        + "id:" + id + ","
        + "res:" + res + ","
        + "}";
    }
}

