
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.config.test;

import com.google.gson.JsonElement;

public final class TbFullTypes {
    private final java.util.HashMap<Integer, com.mumu.game.luban.config.test.DemoType2> _dataMap;
    private final java.util.ArrayList<com.mumu.game.luban.config.test.DemoType2> _dataList;

    public TbFullTypes(JsonElement _buf) {
        _dataMap = new java.util.HashMap<Integer, com.mumu.game.luban.config.test.DemoType2>();
        _dataList = new java.util.ArrayList<com.mumu.game.luban.config.test.DemoType2>();

        for (com.google.gson.JsonElement _e_ : _buf.getAsJsonArray()) {
            com.mumu.game.luban.config.test.DemoType2 _v;
            _v = com.mumu.game.luban.config.test.DemoType2.deserialize(_e_.getAsJsonObject());
            _dataList.add(_v);
            _dataMap.put(_v.x4, _v);
        }
    }

    public java.util.HashMap<Integer, com.mumu.game.luban.config.test.DemoType2> getDataMap() { return _dataMap; }
    public java.util.ArrayList<com.mumu.game.luban.config.test.DemoType2> getDataList() { return _dataList; }

    public com.mumu.game.luban.config.test.DemoType2 get(int key) { return _dataMap.get(key); }

}

