
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.config.test;

import com.google.gson.JsonElement;

public final class TbMultiUnionIndexList {
    private final java.util.ArrayList<com.mumu.game.luban.config.test.MultiUnionIndexList> _dataList;

    public TbMultiUnionIndexList(JsonElement _buf) {
        _dataList = new java.util.ArrayList<com.mumu.game.luban.config.test.MultiUnionIndexList>();

        for (com.google.gson.JsonElement _e_ : _buf.getAsJsonArray()) {
            com.mumu.game.luban.config.test.MultiUnionIndexList _v;
            _v = com.mumu.game.luban.config.test.MultiUnionIndexList.deserialize(_e_.getAsJsonObject());
            _dataList.add(_v);
        }
    }

    public java.util.ArrayList<com.mumu.game.luban.config.test.MultiUnionIndexList> getDataList() { return _dataList; }

    public com.mumu.game.luban.config.test.MultiUnionIndexList get(int index) { return _dataList.get(index); }


}

