
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.config.test;

import com.google.gson.JsonElement;

public final class TbSingleton {
    private final com.mumu.game.luban.config.test.DemoSingletonType _data;

    public final com.mumu.game.luban.config.test.DemoSingletonType data() { return _data; }

    public TbSingleton(JsonElement _buf) {
        int n = _buf.getAsJsonArray().size();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = com.mumu.game.luban.config.test.DemoSingletonType.deserialize(_buf.getAsJsonArray().get(0).getAsJsonObject().getAsJsonObject());
    }


     public int getId() { return _data.id; }
     public String getName() { return _data.name; }
     public com.mumu.game.luban.config.test.DemoDynamic getDate() { return _data.date; }

}

