
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.config.test;

import com.google.gson.JsonObject;
import com.mumu.game.luban.base.AbstractBean;


public final class TestConstAlias extends AbstractBean {
    public TestConstAlias(JsonObject _buf) {
        id = _buf.get("id").getAsInt();
        x1 = _buf.get("x1").getAsInt();
        x2 = _buf.get("x2").getAsLong();
        x3 = _buf.get("x3").getAsFloat();
        x4 = _buf.get("x4").getAsDouble();
    }

    public static TestConstAlias deserialize(JsonObject _buf) {
        return new com.mumu.game.luban.config.test.TestConstAlias(_buf);
    }

    public final int id;
    public final int x1;
    public final long x2;
    public final float x3;
    public final double x4;

    public static final int __ID__ = -498577445;

    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public java.lang.String toString() {
        return "{ "
        + "id:" + id + ","
        + "x1:" + x1 + ","
        + "x2:" + x2 + ","
        + "x3:" + x3 + ","
        + "x4:" + x4 + ","
        + "}";
    }
}

