
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.config.test;

import com.google.gson.JsonObject;
import com.mumu.game.luban.base.AbstractBean;


public final class TestMapper extends AbstractBean {
    public TestMapper(JsonObject _buf) {
        id = _buf.get("id").getAsInt();
        audioType = _buf.get("audio_type").getAsInt();
        v2 = com.mumu.game.luban.config.bean.Vector2.deserialize(_buf.get("v2").getAsJsonObject());
    }

    public static TestMapper deserialize(JsonObject _buf) {
        return new com.mumu.game.luban.config.test.TestMapper(_buf);
    }

    public final int id;
    public final int audioType;
    public final com.mumu.game.luban.config.bean.Vector2 v2;

    public static final int __ID__ = 149110895;

    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public java.lang.String toString() {
        return "{ "
        + "id:" + id + ","
        + "audioType:" + audioType + ","
        + "v2:" + v2 + ","
        + "}";
    }
}

