
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.config.item;

import com.google.gson.JsonElement;

public final class ItemContailTable {
    private final java.util.HashMap<Integer, com.mumu.game.luban.config.item.ItemContail> _dataMap;
    private final java.util.ArrayList<com.mumu.game.luban.config.item.ItemContail> _dataList;

    public ItemContailTable(JsonElement _buf) {
        _dataMap = new java.util.HashMap<Integer, com.mumu.game.luban.config.item.ItemContail>();
        _dataList = new java.util.ArrayList<com.mumu.game.luban.config.item.ItemContail>();

        for (com.google.gson.JsonElement _e_ : _buf.getAsJsonArray()) {
            com.mumu.game.luban.config.item.ItemContail _v;
            _v = com.mumu.game.luban.config.item.ItemContail.deserialize(_e_.getAsJsonObject());
            _dataList.add(_v);
            _dataMap.put(_v.id, _v);
        }
    }

    public java.util.HashMap<Integer, com.mumu.game.luban.config.item.ItemContail> getDataMap() { return _dataMap; }
    public java.util.ArrayList<com.mumu.game.luban.config.item.ItemContail> getDataList() { return _dataList; }

    public com.mumu.game.luban.config.item.ItemContail get(int key) { return _dataMap.get(key); }

}

