
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.config.item;

import com.google.gson.JsonObject;
import com.mumu.game.luban.base.AbstractBean;


public final class ItemContail extends AbstractBean {
    public ItemContail(JsonObject _buf) {
        id = _buf.get("id").getAsInt();
        type = _buf.get("type").getAsInt();
    }

    public static ItemContail deserialize(JsonObject _buf) {
        return new com.mumu.game.luban.config.item.ItemContail(_buf);
    }

    /**
     * id
     */
    public final int id;
    /**
     * 类型
     */
    public final int type;

    public static final int __ID__ = -993784892;

    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public java.lang.String toString() {
        return "{ "
        + "id:" + id + ","
        + "type:" + type + ","
        + "}";
    }
}

