
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.config.demo;

import com.google.gson.JsonObject;
import com.mumu.game.luban.base.AbstractBean;


public final class Demo extends AbstractBean {
    public Demo(JsonObject _buf) {
        id = _buf.get("id").getAsInt();
        name = _buf.get("name").getAsString();
        count = _buf.get("count").getAsInt();
    }

    public static Demo deserialize(JsonObject _buf) {
        return new com.mumu.game.luban.config.demo.Demo(_buf);
    }

    /**
     * id
     */
    public final int id;
    /**
     * 名称
     */
    public final String name;
    /**
     * 个数
     */
    public final int count;

    public static final int __ID__ = 749462318;

    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public java.lang.String toString() {
        return "{ "
        + "id:" + id + ","
        + "name:" + name + ","
        + "count:" + count + ","
        + "}";
    }
}

