
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.config.demo;

import com.google.gson.JsonElement;

public final class DemoTable {
    private final java.util.HashMap<Integer, com.mumu.game.luban.config.demo.Demo> _dataMap;
    private final java.util.ArrayList<com.mumu.game.luban.config.demo.Demo> _dataList;

    public DemoTable(JsonElement _buf) {
        _dataMap = new java.util.HashMap<Integer, com.mumu.game.luban.config.demo.Demo>();
        _dataList = new java.util.ArrayList<com.mumu.game.luban.config.demo.Demo>();

        for (com.google.gson.JsonElement _e_ : _buf.getAsJsonArray()) {
            com.mumu.game.luban.config.demo.Demo _v;
            _v = com.mumu.game.luban.config.demo.Demo.deserialize(_e_.getAsJsonObject());
            _dataList.add(_v);
            _dataMap.put(_v.id, _v);
        }
    }

    public java.util.HashMap<Integer, com.mumu.game.luban.config.demo.Demo> getDataMap() { return _dataMap; }
    public java.util.ArrayList<com.mumu.game.luban.config.demo.Demo> getDataList() { return _dataList; }

    public com.mumu.game.luban.config.demo.Demo get(int key) { return _dataMap.get(key); }

}

