
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.config.demo;

import luban.*;
import com.google.gson.JsonElement;


public final class TbItem2 {
    private final java.util.HashMap<Integer, com.mumu.game.luban.config.demo.Item2> _dataMap;
    private final java.util.ArrayList<com.mumu.game.luban.config.demo.Item2> _dataList;
    
    public TbItem2(JsonElement _buf) {
        _dataMap = new java.util.HashMap<Integer, com.mumu.game.luban.config.demo.Item2>();
        _dataList = new java.util.ArrayList<com.mumu.game.luban.config.demo.Item2>();
        
        for (com.google.gson.JsonElement _e_ : _buf.getAsJsonArray()) {
            com.mumu.game.luban.config.demo.Item2 _v;
            _v = com.mumu.game.luban.config.demo.Item2.deserialize(_e_.getAsJsonObject());
            _dataList.add(_v);
            _dataMap.put(_v.id, _v);
        }
    }

    public java.util.HashMap<Integer, com.mumu.game.luban.config.demo.Item2> getDataMap() { return _dataMap; }
    public java.util.ArrayList<com.mumu.game.luban.config.demo.Item2> getDataList() { return _dataList; }

    public com.mumu.game.luban.config.demo.Item2 get(int key) { return _dataMap.get(key); }

}
