
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.config.activity;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.mumu.game.luban.base.AbstractBean;


public final class Activity extends AbstractBean {
    public Activity(JsonObject _buf) {
        id = _buf.get("id").getAsInt();
        functionId = _buf.get("function_id").getAsInt();
        showTime = _buf.get("show_time").getAsLong();
        startTime = _buf.get("start_time").getAsLong();
        endTime = _buf.get("end_time").getAsLong();
        { com.google.gson.JsonArray _json0_ = _buf.get("clear_item_ids").getAsJsonArray(); clearItemIds = new java.util.ArrayList<Integer>(_json0_.size()); for(JsonElement _e0 : _json0_) { int _v0;  _v0 = _e0.getAsInt();  clearItemIds.add(_v0); }   }
    }

    public static Activity deserialize(JsonObject _buf) {
        return new com.mumu.game.luban.config.activity.Activity(_buf);
    }

    /**
     * 主键
     */
    public final int id;
    /**
     * 功能id
     */
    public final int functionId;
    /**
     * 活动展示时间
     */
    public final long showTime;
    /**
     * 活动开始时间
     */
    public final long startTime;
    /**
     * 活动结束时间
     */
    public final long endTime;
    /**
     * 活动结束需要被清理的道具id列表
     */
    public final java.util.ArrayList<Integer> clearItemIds;

    public static final int __ID__ = 1932875566;

    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public java.lang.String toString() {
        return "{ "
        + "id:" + id + ","
        + "functionId:" + functionId + ","
        + "showTime:" + showTime + ","
        + "startTime:" + startTime + ","
        + "endTime:" + endTime + ","
        + "clearItemIds:" + clearItemIds + ","
        + "}";
    }
}

