
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.config.activity;

import com.google.gson.JsonElement;

public final class ActivityTable {
    private final java.util.HashMap<Integer, com.mumu.game.luban.config.activity.Activity> _dataMap;
    private final java.util.ArrayList<com.mumu.game.luban.config.activity.Activity> _dataList;

    public ActivityTable(JsonElement _buf) {
        _dataMap = new java.util.HashMap<Integer, com.mumu.game.luban.config.activity.Activity>();
        _dataList = new java.util.ArrayList<com.mumu.game.luban.config.activity.Activity>();

        for (com.google.gson.JsonElement _e_ : _buf.getAsJsonArray()) {
            com.mumu.game.luban.config.activity.Activity _v;
            _v = com.mumu.game.luban.config.activity.Activity.deserialize(_e_.getAsJsonObject());
            _dataList.add(_v);
            _dataMap.put(_v.id, _v);
        }
    }

    public java.util.HashMap<Integer, com.mumu.game.luban.config.activity.Activity> getDataMap() { return _dataMap; }
    public java.util.ArrayList<com.mumu.game.luban.config.activity.Activity> getDataList() { return _dataList; }

    public com.mumu.game.luban.config.activity.Activity get(int key) { return _dataMap.get(key); }

}

