application:
  name: gateway

# web端口号
server:
  port: 7002

# 指定logback配置文件
logging:
  config: classpath:logback-spring.xml

spring:
  data:
    # 配置redis信息
    redis:
      host: r-uf6jzg20l7dcc3nstlpd.redis.rds.aliyuncs.com
      port: 6379
      password: PtfR4duIAGnW5jQk
      database: 10
      connect-timeout: 3000
      lettuce:
        pool:
          max-active: 512
          min-idle: 5
          max-idle: 128
          max-wait: 3000

    # 以下是配置数据库mongodb的信息
    mongodb:
      host: 115.28.208.195
      port: 27017
      username: my-game
      password: xxx123456
      authentication-database: admin
      database: my-game

# 游戏网络自定义配置
net:
  # 版本号
  version: 0
  # 服务id
  serverId: 2000
  # 服务器类型
  serviceType: GATEWAY
  server:
    enable: true
    # 当前服务器 ip
    host: 127.0.0.1
    port: 8200
    protocol: socket
    bossThreadNum: 1
    workThreadNum: 64
    soBacklog: 128
    soKeepalive: true
    tcpNoDelay: false
  client:
    enable: true
    protocol: socket
    clientThreadNum: 64
    soKeepalive: true
    tcpNoDelay: false
  register:
    enable: true
    retryCount: 20
    servers:
      - ip: 192.168.1.183
        port: 8100
  thread:
    enable: true
    player-core-pool-size: 64

# 游戏配置
game:
  # 游戏通用配置
  common:
    # groovy 脚本
    groovy:
      # 是否开启
      enable: true
      # groovy 脚本路径
      groovyPath: /data/groovy