
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.config;

import luban.*;
import com.google.gson.JsonElement;

public final class LubanTables
{

    public  interface  IJsonLoader {
        JsonElement load(String file) throws java.io.IOException;
    }

    private final com.mumu.game.luban.config.demo.TbItem2 _tbitem2;
    public com.mumu.game.luban.config.demo.TbItem2 getTbItem2() { return _tbitem2; }

    public LubanTables(IJsonLoader loader) throws java.io.IOException {
        _tbitem2 = new com.mumu.game.luban.config.demo.TbItem2(loader.load("demo_tbitem2")); 
    }
}

