
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.config.function;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.mumu.game.luban.base.AbstractBean;


public final class Function extends AbstractBean {
    public Function(JsonObject _buf) {
        id = _buf.get("id").getAsInt();
        parentId = _buf.get("parent_id").getAsInt();
        name = _buf.get("name").getAsString();
        desc = _buf.get("desc").getAsString();
        condition = _buf.get("condition").getAsString();
        close = _buf.get("close").getAsBoolean();
        sort = _buf.get("sort").getAsInt();
        extraInfo = _buf.get("extra_info").getAsString();
    }

    public static Function deserialize(JsonObject _buf) {
        return new com.mumu.game.luban.config.function.Function(_buf);
    }

    /**
     * 功能id
     */
    public final int id;
    /**
     * 父功能id
     */
    public final int parentId;
    /**
     * 名称
     */
    public final String name;
    /**
     * 描述
     */
    public final String desc;
    /**
     * 功能开启条件
     */
    public final String condition;
    /**
     * 是否关闭（总开关）
     */
    public final boolean close;
    /**
     * 排序
     */
    public final int sort;
    /**
     * 功能额外信息
     */
    public final String extraInfo;

    public static final int __ID__ = -321967794;

    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public java.lang.String toString() {
        return "{ "
        + "id:" + id + ","
        + "parentId:" + parentId + ","
        + "name:" + name + ","
        + "desc:" + desc + ","
        + "condition:" + condition + ","
        + "close:" + close + ","
        + "sort:" + sort + ","
        + "extraInfo:" + extraInfo + ","
        + "}";
    }
}

