
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.config.function;

import com.google.gson.JsonElement;

public final class FunctionTable {
    private final java.util.HashMap<Integer, com.mumu.game.luban.config.function.Function> _dataMap;
    private final java.util.ArrayList<com.mumu.game.luban.config.function.Function> _dataList;

    public FunctionTable(JsonElement _buf) {
        _dataMap = new java.util.HashMap<Integer, com.mumu.game.luban.config.function.Function>();
        _dataList = new java.util.ArrayList<com.mumu.game.luban.config.function.Function>();

        for (com.google.gson.JsonElement _e_ : _buf.getAsJsonArray()) {
            com.mumu.game.luban.config.function.Function _v;
            _v = com.mumu.game.luban.config.function.Function.deserialize(_e_.getAsJsonObject());
            _dataList.add(_v);
            _dataMap.put(_v.id, _v);
        }
    }

    public java.util.HashMap<Integer, com.mumu.game.luban.config.function.Function> getDataMap() { return _dataMap; }
    public java.util.ArrayList<com.mumu.game.luban.config.function.Function> getDataList() { return _dataList; }

    public com.mumu.game.luban.config.function.Function get(int key) { return _dataMap.get(key); }

}

