
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.config.bean;

import luban.*;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;


public final class Vector3 extends AbstractBean {
    public Vector3(JsonObject _buf) { 
        x = _buf.get("x").getAsFloat();
        y = _buf.get("y").getAsFloat();
        z = _buf.get("z").getAsFloat();
    }

    public static Vector3 deserialize(JsonObject _buf) {
            return new com.mumu.game.luban.config.bean.Vector3(_buf);
    }

    public final float x;
    public final float y;
    public final float z;

    public static final int __ID__ = 390615794;
    
    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public String toString() {
        return "{ "
        + "x:" + x + ","
        + "y:" + y + ","
        + "z:" + z + ","
        + "}";
    }
}

