syntax = "proto3";

option java_package = "com.game.proto.function";

import "item/item.proto";


// 请求获取功能状态信息列表
message CWGetFunctionStateListMessage {
  /** 功能id(0为全部功能) */
  int32 functionId = 1;
}

// 响应获取功能状态信息列表
message WCGetFunctionStateListMessage {
  /** 功能列表(此功能以及所有子功能) */
  repeated SingleFunctionInfoBean singleFunctionInfoBeanList = 1;
}

// 推送功能状态变更消息
message OnPushFunctionStateListMessage {
  /**功能id(0为全部功能) */
  int32 functionId = 1;
  /** 功能列表(此功能以及所有子功能) */
  repeated SingleFunctionInfoBean singleFunctionInfoBeanList = 2;
}

// 功能信息
message SingleFunctionInfoBean {
  /** 功能id */
  int32 functionId = 1;
  /** 是否开放 */
  bool hasOpen = 2;
  /** 是否有红点 */
  bool hasRedPoint = 3;
  /** 开放的活动组件ID列表 */
  repeated int32 activityIds = 4;
  /** 赛季开始时间，无默认-1 */
  int64 startTime = 5;
  /** 赛季结束时间，无默认-1 */
  int64 endTime = 6;
  /** 参数。注：只用于记录简单数据，复杂信息走协议！ */
  string param = 7;
  /** 功能配置基本信息 */
  ConfigFunctionInfoBean configFunctionInfoBean = 8;
}

// 功能配置基本信息
message ConfigFunctionInfoBean {
  /** 父功能id */
  int32 parentId = 1;
  /** 名称 */
  string name = 2;
  /** 描述 */
  string desc = 3;
  /** 是否关闭 */
  bool close = 4;
  /** 排序 */
  int32 sort = 9;
  /** 功能额外信息( type:value;type:value;  已有类型：type-0, value-活动预热时间(单位分钟)  */
  string extraInfo = 10;
}

// 请求消除功能红点消息
message CWClearFuncRedPointMessage {
  /** 功能id */
  int32 functionId = 1;
  /** 参数0 */
  optional int32 arg0 = 2;
  /** 参数1 */
  string arg1 = 3;
}

// 响应消除功能红点消息
message WCClearFuncRedPointMessage {
}

// 请求获取功能列表By功能类型
message CWGetFunctionIdListByTypeMessage {
  /** 功能类型 0: 活动列表 */
  int32 type = 1;
  /** 构建配置信息 */
  optional bool buildConfig = 2;
}

// 响应获取功能列表By功能类型
message WCGetFunctionIdListByTypeMessage {
  /** 活动功能信息bean列表 */
  repeated ActivityFunctionInfoBean activityBannerBeanList = 1;
}

// 请求获取子功能id列表消息
message CWGetSubFunctionIdListMessage {
  /** 功能id */
  int32 functionId = 1;
}

// 响应获取子功能id列表消息
message WCGetSubFunctionIdListMessage {
  /** 活动功能信息bean列表 */
  repeated ActivityFunctionInfoBean activityBannerBeanList = 1;
}

// 活动功能信息bean
message ActivityFunctionInfoBean {
  /** 功能id */
  int32 functionId = 1;
  /** 功能配置基本信息 */
  ConfigFunctionInfoBean configFunctionInfoBean = 2;
}


// ConfigFunctionInfo配置表变更通知推送
message OnWCPushConfigFuncUpdateMessage {
}