
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.cfg;

import com.google.gson.JsonElement;

public final class CfgTables
{

    public  interface  IJsonLoader {
        JsonElement load(String file) throws java.io.IOException;
    }

    private final com.mumu.game.luban.cfg.demo.TbItem _tbitem;
    public com.mumu.game.luban.cfg.demo.TbItem getTbItem() { return _tbitem; }

    public CfgTables(IJsonLoader loader) throws java.io.IOException {
        _tbitem = new com.mumu.game.luban.cfg.demo.TbItem(loader.load("demo_tbitem")); 
    }
}

