
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.mumu.game.luban.cfg.demo;

import luban.*;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;


public final class item extends AbstractBean {
    public item(JsonObject _buf) { 
        id = _buf.get("id").getAsInt();
        name = _buf.get("name").getAsString();
        count = _buf.get("count").getAsInt();
    }

    public static item deserialize(JsonObject _buf) {
            return new com.mumu.game.luban.cfg.demo.item(_buf);
    }

    /**
     * id
     */
    public final int id;
    /**
     * 名称
     */
    public final String name;
    /**
     * 个数
     */
    public final int count;

    public static final int __ID__ = 750578750;
    
    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public String toString() {
        return "{ "
        + "id:" + id + ","
        + "name:" + name + ","
        + "count:" + count + ","
        + "}";
    }
}

