application:
  # 应用名称
  name: game-server

# web端口号
server:
  port: 8388

# 指定logback配置文件
logging:
  config: classpath:logback-local.xml

spring:
  data:
    # 配置redis信息
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 0
      # 连接超时时间（毫秒）
      connect-timeout: 3000
      lettuce:
        pool:
          # 连接池最大活跃连接数
          max-active: 512
          # 连接池最小空闲连接数
          min-idle: 5
          # 连接池最大空闲连接数
          max-idle: 128
          # 连接池获取连接最大等待时间（毫秒）
          max-wait: 3000
    # 以下是配置数据库mongodb的信息
    mongodb:
        host: 127.0.0.1  # MongoDB服务器地址
        port: 27017  # MongoDB服务器端口
        username: my-game  # MongoDB用户名
        password:  # MongoDB密码（为空表示无密码）
        authentication-database: admin  # 认证数据库
        database: my-game  # 业务数据库名称

# 游戏网络自定义配置
net:
  # 当前服务器版本号
  version: 0
  # 当前服务器ID（唯一标识）
  serverId: 3000
  # 服务器类型
  serviceType: GAME
  # Netty服务器配置（接收客户端连接）
  server:
    # 是否启用Netty服务器
    enable: true
    # 当前服务器 ip
    host: 127.0.0.1
    port: 8300
    protocol: socket
    bossThreadNum: 1
    workThreadNum: 64
    soBacklog: 128
    soKeepalive: true
    tcpNoDelay: false
  client:
    # 是否启用Netty客户端
    enable: true
    # 通信协议
    protocol: socket
    # 客户端IO线程数
    clientThreadNum: 64
    # 是否开启TCP心跳保活
    soKeepalive: true
    # 是否禁用Nagle算法
    tcpNoDelay: false
  # 业务线程池配置
  thread:
    # 是否启用自定义线程池
    enable: true
    # 玩家业务线程池核心线程数
    player-core-pool-size: 64

# 游戏通用配置
game:
  # 游戏通用配置
  common:
    # Groovy动态脚本配置
    groovy:
      # 是否启用Groovy热更新脚本
      enable: true
      # Groovy脚本存放路径
      groovyPath: /data/groovy